# Generated by Django 3.2.25 on 2025-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='glicko_rating',
            field=models.FloatField(default=1500.0),
        ),
    ]
