# Generated by Django 3.2.25 on 2025-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tournamentplayer_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, to='core.BasePlayer'),
        ),
    ]
