# Generated by Django 3.2.25 on 2025-03-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevent',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tevent',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
