# Generated by Django 3.2.25 on 2025-03-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250311_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevent',
            name='end_date',
            field=models.DateField(blank=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tevent',
            name='start_date',
            field=models.DateField(blank=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
