# Generated by Django 3.2.25 on 2025-03-19 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250314_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevent',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tevent',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
